name: Deploy to github pages
on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master
jobs:
    gh-pages-deploy:
        name: Deploying to gh-pages
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js for use with actions
              uses: actions/setup-node@v1
              with:
                  node-version: "12"
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Clean install dependencies
              working-directory: ./
              run: npm ci

            - name: Run deploy script
              working-directory: ./
              run: |
                  git config user.name "PavelescuVictor" && git config user.email "pavelescu.victor97@gmail.com"
                  npm run gh-pages-deploy